<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INBANGNBLENO10" name="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest" tests="20" failures="6" timestamp="23 Oct 2018 20:35:25 GMT" time="256.965" errors="0">
  <testcase name="test15_EnterSoldItemsUnCompressed" time="10.511" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest">
    <failure type="java.lang.AssertionError" message="Business location mismatch for the epc:3034186A940B96000000001E, Expected:null,Actual:StoreMFT1_ShippingArea">
      <![CDATA[java.lang.AssertionError: Business location mismatch for the epc:3034186A940B96000000001E, Expected:null,Actual:StoreMFT1_ShippingArea
at org.junit.Assert.fail(Assert.java:88)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifiyEPCInfo(MVHHMsgCommon.java:334)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifyData(MVHHMsgCommon.java:311)
at com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest.test15_EnterSoldItemsUnCompressed(MF01_SingleMsgTest.java:186)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test15_EnterSoldItemsUnCompressed -->
  <testcase name="test08_NCCNonStreamCompressed" time="8.090" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test01_ReceivingUntaggedUnCompressed" time="9.373" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test03_ReceivingTaggedUnCompressed" time="7.070" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test02_ReceivingUntaggedCompressed" time="8.558" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test14_FCCStreamCompressed" time="11.710" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test20_EncodeItemsCompressed" time="45.237" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest">
    <failure type="java.lang.AssertionError" message="Message processing is not completed.">
      <![CDATA[java.lang.AssertionError: Message processing is not completed.
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifyData(MVHHMsgCommon.java:306)
at com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest.test20_EncodeItemsCompressed(MF01_SingleMsgTest.java:238)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test20_EncodeItemsCompressed -->
  <testcase name="test13_FCCStreamUnCompressed" time="12.344" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test04_ReceivingTaggedCompressed" time="7.314" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test06_PutAwayCompressed" time="7.311" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test16_EnterSoldItemsCompressed" time="9.437" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest">
    <failure type="java.lang.AssertionError" message="Business location mismatch for the epc:3034186A940B960000000020, Expected:null,Actual:StoreMFT1_ShippingArea">
      <![CDATA[java.lang.AssertionError: Business location mismatch for the epc:3034186A940B960000000020, Expected:null,Actual:StoreMFT1_ShippingArea
at org.junit.Assert.fail(Assert.java:88)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifiyEPCInfo(MVHHMsgCommon.java:334)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifyData(MVHHMsgCommon.java:311)
at com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest.test16_EnterSoldItemsCompressed(MF01_SingleMsgTest.java:195)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test16_EnterSoldItemsCompressed -->
  <testcase name="test11_FCCNonStreamUnCompressed" time="8.277" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test18_RetirementCompressed" time="7.800" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest">
    <failure type="java.lang.AssertionError" message="Business location mismatch for the epc:3034186A940B960000000024, Expected:null,Actual:StoreMFT1_ShippingArea">
      <![CDATA[java.lang.AssertionError: Business location mismatch for the epc:3034186A940B960000000024, Expected:null,Actual:StoreMFT1_ShippingArea
at org.junit.Assert.fail(Assert.java:88)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifiyEPCInfo(MVHHMsgCommon.java:334)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifyData(MVHHMsgCommon.java:311)
at com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest.test18_RetirementCompressed(MF01_SingleMsgTest.java:217)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test18_RetirementCompressed -->
  <testcase name="test12_FCCNonStreamCompressed" time="8.886" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test19_EncodeItemsUnCompressed" time="45.157" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest">
    <failure type="java.lang.AssertionError" message="Message processing is not completed.">
      <![CDATA[java.lang.AssertionError: Message processing is not completed.
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifyData(MVHHMsgCommon.java:306)
at com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest.test19_EncodeItemsUnCompressed(MF01_SingleMsgTest.java:230)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test19_EncodeItemsUnCompressed -->
  <testcase name="test09_NCCStreamUnCompressed" time="13.284" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test10_NCCStreamCompressed" time="11.397" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test05_PutAwayUnCompressed" time="9.240" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
  <testcase name="test17_RetirementUnCompressed" time="8.267" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest">
    <failure type="java.lang.AssertionError" message="Business location mismatch for the epc:3034186A940B960000000022, Expected:null,Actual:StoreMFT1_ShippingArea">
      <![CDATA[java.lang.AssertionError: Business location mismatch for the epc:3034186A940B960000000022, Expected:null,Actual:StoreMFT1_ShippingArea
at org.junit.Assert.fail(Assert.java:88)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifiyEPCInfo(MVHHMsgCommon.java:334)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifyData(MVHHMsgCommon.java:311)
at com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest.test17_RetirementUnCompressed(MF01_SingleMsgTest.java:204)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test17_RetirementUnCompressed -->
  <testcase name="test07_NCCNonStreamUnCompressed" time="7.702" classname="com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest"/>
</testsuite> <!-- com.oatsystems.test.mv.hhmsgs.MF01_SingleMsgTest -->
