<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INBANGNBLENO10" name="com.chkpoint.jaytest1.Inventory_Test_UnknownValid" tests="4" failures="0" timestamp="24 Oct 2018 10:23:48 GMT" time="241.993" errors="0">
  <testcase name="Test03ReceiveRetireThenReturnAtSameLocation" time="64.942" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownValid"/>
  <testcase name="Test01ReceiveRetireThenCycleCountAtSameLocation" time="53.193" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownValid"/>
  <testcase name="Test02ReceiveRetireThenPutawayAtSameLocation" time="60.673" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownValid"/>
  <testcase name="Test04ReceiveRetireThenRetireAtSameLocation" time="63.185" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownValid"/>
</testsuite> <!-- com.chkpoint.jaytest1.Inventory_Test_UnknownValid -->
